### ISSUE TITLE
Something is wrong with README.TXT

### ISSUE THREAD

**Issue by sanchesfree** [llSourcell/ChatGPT_Clone#1]
`3. Change line 55 URL to localhost:3080`

Which file are we talking about? I couldn't find it on my own.

p.s. You did good)

**Comment by ykk648** [comment]
https://github.com/llSourcell/ChatGPT_Clone/blob/e0e1fb57a532d568695274d2433ef12eab90482d/api/index.js#L11

**Comment by ykk648** [comment]
https://github.com/llSourcell/ChatGPT_Clone/blob/e0e1fb57a532d568695274d2433ef12eab90482d/client/src/App.js#L31
